engine:
  mode : translate # parser / translate

parser: #爬虫
  keyward : few-shot,Incremental Learning # 逗号分割
  aim : conf/cvpr,conf/aaai,conf/ijcai,conf/acm,conf/pmlr # 逗号分割
  year : 2024-2025 # 不填/2023/2022-2023
  output_file_path : ./output.docx # 输出文件路径

translate: #翻译
  translate_mode : qwen # openai / deepseek / qwen
  # OpenAI配置
  openai_key : 
  openai_host : 
  model : gpt-3.5-turbo-0125
  
  # 硅基流动配置
  deepseek_key : sk-rcaebgtcmaynkmxuhbalsziktwlyhltlbwlhdhrfysnkmbcy
  deepseek_host : https://api.siliconflow.cn/v1
  deepseek_model : Pro/deepseek-ai/DeepSeek-R1
  
  # 通义千问配置（通过硅基流动调用）
  qwen_key : sk-rcaebgtcmaynkmxuhbalsziktwlyhltlbwlhdhrfysnkmbcy
  qwen_host : https://api.siliconflow.cn/v1
  qwen_model : Qwen/Qwen2.5-72B-Instruct
  
  translate_file : ./output.docx # 输入文件路径
  output_file_path : ./output_zh.docx # 输出文件路径
  
system:
  quiet_mode : False
  retry : 3
  delay : 1